name: ciga_process_app
description: Application de Diagnostic et de Plan d'Action Synergie Ã‰volutive.
publish_to: 'none'

version: 1.0.0+1

environment:
sdk: '>=3.0.0 <4.0.0'

dependencies:
flutter:
sdk: flutter

DÃ©pendances essentielles

cupertino_icons: ^1.0.2

DÃ©pendances pour l'API, la validation, et le stockage

http: ^1.1.0

CORRECTION CRITIQUE : La version a Ã©tÃ© abaissÃ©e de ^2.1.18 Ã  ^2.1.17 pour rÃ©soudre le conflit.

email_validator: ^2.1.17
shared_preferences: ^2.2.2

ðŸš€ DÃ©pendances pour la gÃ©nÃ©ration et le partage de PDF

pdf: ^3.10.8

printing: ^5.11.1

path_provider: ^2.1.1

open_file: ^3.3.2

dev_dependencies:
flutter_test:
sdk: flutter
flutter_lints: ^2.0.0

flutter:
uses-material-design: true

ðŸ–¼ï¸ DÃ©claration des Assets

assets:
- assets/logo.png